import type { Config } from 'tailwindcss'

const config: Config = {
	content: ['./pages/**/*.{js,ts,jsx,tsx,mdx}', './components/**/*.{js,ts,jsx,tsx,mdx}', './app/**/*.{js,ts,jsx,tsx,mdx}'],
	theme: {
		colors: {
			green: {
				1: 'var(--green-1)',
				2: 'var(--green-2)',
				3: 'var(--green-3)',
				4: 'var(--green-4)',
				5: 'var(--green-5)',
				6: 'var(--green-6)',
				7: 'var(--green-7)',
				8: 'var(--green-8)',
				9: 'var(--green-9)',
				10: 'var(--green-10)',
				11: 'var(--green-11)',
				12: 'var(--green-12)',
			},
			gray: {
				1: 'var(--gray-1)',
				2: 'var(--gray-2)',
				3: 'var(--gray-3)',
				4: 'var(--gray-4)',
				5: 'var(--gray-5)',
				6: 'var(--gray-6)',
				7: 'var(--gray-7)',
				8: 'var(--gray-8)',
				9: 'var(--gray-9)',
				10: 'var(--gray-10)',
				11: 'var(--gray-11)',
				12: 'var(--gray-12)',
			},
			'green-a': {
				1: 'var(--green-a1)',
				2: 'var(--green-a2)',
				3: 'var(--green-a3)',
				4: 'var(--green-a4)',
				5: 'var(--green-a5)',
				6: 'var(--green-a6)',
				7: 'var(--green-a7)',
				8: 'var(--green-a8)',
				9: 'var(--green-a9)',
				10: 'var(--green-a10)',
				11: 'var(--green-a11)',
				12: 'var(--green-a12)',
			},
			'gray-a': {
				1: 'var(--gray-a1)',
				2: 'var(--gray-a2)',
				3: 'var(--gray-a3)',
				4: 'var(--gray-a4)',
				5: 'var(--gray-a5)',
				6: 'var(--gray-a6)',
				7: 'var(--gray-a7)',
				8: 'var(--gray-a8)',
				9: 'var(--gray-a9)',
				10: 'var(--gray-a10)',
				11: 'var(--gray-a11)',
				12: 'var(--gray-a12)',
			},
			'green-contrast': 'var(--green-contrast)',
			'green-surface': 'var(--green-surface)',
			'green-indicator': 'var(--green-indicator)',
			'green-track': 'var(--green-track)',
			'gray-contrast': 'var(--gray-contrast)',
			'gray-surface': 'var(--gray-surface)',
			'gray-indicator': 'var(--gray-indicator)',
			'gray-track': 'var(--gray-track)',
		},
		screens: {
			xs: '480px',
			sm: '640px',
			md: '768px',
			lg: '960px',
			xl: '1024px',
			xxl: '1280px',
			xxxl: '1536px',
		},
	},
	plugins: [],
}
export default config
